#**********************************************************************  
#	*주의 사항
#		현재 스크립트 파일은 파일명만 출력되어 있습니다.
#		따라서, 저장된 추출 결과 파일의 경로를 'read.table' 또는 'read.fwf'에 추가하여야 합니다.
#	예) 다운로드 받은 폴더명 : C:\Download
#	  ※ 파일 경로 추가 : "[다운로드 받은 폴더명]\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt"
# 		read.table("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#		또는
#		read.fwf("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#
#		R 스크립트는 R 에서 파일 경로만 수정하시면 바로 실행(Ctrl+Alt+R)가능하며,
#		데이터셋 생성 후에 R 의 여러 가지 분석 기능을 사용할 수 있습니다.
#
#**********************************************************************

install.packages("dplyr")
library(dplyr)

mdis <- read.table("1960_2%_인구사항_20250821_54801.csv", header=FALSE, sep=",", colClasses = c("character"
, "numeric", "character", "numeric", "character", "numeric", "character", "character", "character", "character", "numeric", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character"
, "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric"
, "numeric", "character", "character", "character", "character", "character", "character", "numeric"), skip=1, na.string=c("*","**","***","****","*****","******","*******","********","*********","**********","."))

        mdis$V1<- recode_factor(mdis$V1, '0'="서울특별시")
        mdis$V1<- recode_factor(mdis$V1, '1'="경기도")
        mdis$V1<- recode_factor(mdis$V1, '2'="충청북도")
        mdis$V1<- recode_factor(mdis$V1, '3'="충청남도")
        mdis$V1<- recode_factor(mdis$V1, '4'="전라북도")
        mdis$V1<- recode_factor(mdis$V1, '5'="전라남도")
        mdis$V1<- recode_factor(mdis$V1, '6'="경상북도")
        mdis$V1<- recode_factor(mdis$V1, '7'="경상남도")
        mdis$V1<- recode_factor(mdis$V1, '8'="강원도")
        mdis$V1<- recode_factor(mdis$V1, '9'="제주도")
        mdis$V3<- recode_factor(mdis$V3, '1'="영농가구원")
        mdis$V3<- recode_factor(mdis$V3, '2'="비영농가구원")
        mdis$V5<- recode_factor(mdis$V5, '0'="집단가구원")
        mdis$V5<- recode_factor(mdis$V5, '1'="가구주(집단가구대표자)")
        mdis$V5<- recode_factor(mdis$V5, '2'="배우자")
        mdis$V5<- recode_factor(mdis$V5, '3'="아들")
        mdis$V5<- recode_factor(mdis$V5, '4'="딸")
        mdis$V5<- recode_factor(mdis$V5, '5'="손")
        mdis$V5<- recode_factor(mdis$V5, '6'="부모")
        mdis$V5<- recode_factor(mdis$V5, '7'="조부모")
        mdis$V5<- recode_factor(mdis$V5, '8'="친족")
        mdis$V5<- recode_factor(mdis$V5, '9'="동거인")
        mdis$V7<- recode_factor(mdis$V7, '1'="남자")
        mdis$V7<- recode_factor(mdis$V7, '2'="여자")
        mdis$V8<- recode_factor(mdis$V8, '1'=" 유배우")
        mdis$V8<- recode_factor(mdis$V8, '2'=" 사별")
        mdis$V8<- recode_factor(mdis$V8, '3'=" 이혼")
        mdis$V8<- recode_factor(mdis$V8, '4'=" 미혼")
        mdis$V9<- recode_factor(mdis$V9, '0'="서울특별시")
        mdis$V9<- recode_factor(mdis$V9, '1'="경기도")
        mdis$V9<- recode_factor(mdis$V9, '2'="강원도")
        mdis$V9<- recode_factor(mdis$V9, '3'="충청북도")
        mdis$V9<- recode_factor(mdis$V9, '4'="충청남도")
        mdis$V9<- recode_factor(mdis$V9, '5'="전라북도")
        mdis$V9<- recode_factor(mdis$V9, '6'="전라남도")
        mdis$V9<- recode_factor(mdis$V9, '7'="경상북도")
        mdis$V9<- recode_factor(mdis$V9, '8'="경상남도")
        mdis$V9<- recode_factor(mdis$V9, '9'="제주도")
        mdis$V10<- recode_factor(mdis$V10, '1'="한국인")
        mdis$V10<- recode_factor(mdis$V10, '2'="중국인")
        mdis$V10<- recode_factor(mdis$V10, '3'="그외외국인")
        mdis$V12<- recode_factor(mdis$V12, '1'="학교에 다닌다")
        mdis$V12<- recode_factor(mdis$V12, '2'="학교에 안다닌다")
        mdis$V13<- recode_factor(mdis$V13, '0'="0년")
        mdis$V13<- recode_factor(mdis$V13, '1'="1년")
        mdis$V13<- recode_factor(mdis$V13, '2'="2년")
        mdis$V13<- recode_factor(mdis$V13, '3'="3년")
        mdis$V13<- recode_factor(mdis$V13, '4'="4년")
        mdis$V13<- recode_factor(mdis$V13, '5'="5년")
        mdis$V13<- recode_factor(mdis$V13, '6'="6년")
        mdis$V13<- recode_factor(mdis$V13, '7'="7년")
        mdis$V13<- recode_factor(mdis$V13, '8'="8년")
        mdis$V13<- recode_factor(mdis$V13, '9'="9년")
        mdis$V13<- recode_factor(mdis$V13, '10'="10년")
        mdis$V13<- recode_factor(mdis$V13, '11'="11년")
        mdis$V13<- recode_factor(mdis$V13, '12'="12년")
        mdis$V13<- recode_factor(mdis$V13, '13'="13년")
        mdis$V13<- recode_factor(mdis$V13, '14'="14년")
        mdis$V13<- recode_factor(mdis$V13, '15'="15년")
        mdis$V13<- recode_factor(mdis$V13, '16'="16년")
        mdis$V13<- recode_factor(mdis$V13, '17'="17년이상")
        mdis$V13<- recode_factor(mdis$V13, '99'="해당없음(6세이하) 또는 미상")
        mdis$V14<- recode_factor(mdis$V14, '1'="읽고 쓸줄 안다")
        mdis$V14<- recode_factor(mdis$V14, '2'="읽고 쓸줄 모른다")
        mdis$V15<- recode_factor(mdis$V15, '1'="취업")
        mdis$V15<- recode_factor(mdis$V15, '2'="가사")
        mdis$V15<- recode_factor(mdis$V15, '3'="취학")
        mdis$V15<- recode_factor(mdis$V15, '4'="기타")
        mdis$V16<- recode_factor(mdis$V16, '1'="일하였음")
        mdis$V16<- recode_factor(mdis$V16, '2'="일하지 않았음")
        mdis$V17<- recode_factor(mdis$V17, '1'="일거리를 구하여 보았음")
        mdis$V17<- recode_factor(mdis$V17, '2'="일거리를 구하여 보지도 않았음")
        mdis$V18<- recode_factor(mdis$V18, '1'="가사")
        mdis$V18<- recode_factor(mdis$V18, '2'="취학")
        mdis$V18<- recode_factor(mdis$V18, '3'="은퇴")
        mdis$V18<- recode_factor(mdis$V18, '4'="불구")
        mdis$V18<- recode_factor(mdis$V18, '5'="일시적병")
        mdis$V18<- recode_factor(mdis$V18, '6'="구직단념")
        mdis$V18<- recode_factor(mdis$V18, '7'="일기불순")
        mdis$V18<- recode_factor(mdis$V18, '8'="일시휴직")
        mdis$V18<- recode_factor(mdis$V18, '9'="기타")
        mdis$V19<- recode_factor(mdis$V19, '0'="전문적, 기술적 직업")
        mdis$V19<- recode_factor(mdis$V19, '1'="관리적 직업")
        mdis$V19<- recode_factor(mdis$V19, '2'="사무종")
        mdis$V19<- recode_factor(mdis$V19, '3'="판매종")
        mdis$V19<- recode_factor(mdis$V19, '4'="농부, 어부, 벌목부,수렵부 및 유사직업")
        mdis$V19<- recode_factor(mdis$V19, '5'="광부, 채석부 및 유사직업")
        mdis$V19<- recode_factor(mdis$V19, '6'="교통 및 통신업 종사자")
        mdis$V19<- recode_factor(mdis$V19, '7'="기능공, 생업공정 종사자 및 기타단순노무자")
        mdis$V19<- recode_factor(mdis$V19, '8'="기능공, 생업공정 종사자 및 기타단순노무자")
        mdis$V19<- recode_factor(mdis$V19, '9'="서비스 직업종사자")
        mdis$V20<- recode_factor(mdis$V20, '0'="농업, 임업, 수렵업 및 어업")
        mdis$V20<- recode_factor(mdis$V20, '1'="광업 및 채석업")
        mdis$V20<- recode_factor(mdis$V20, '2'="제조업")
        mdis$V20<- recode_factor(mdis$V20, '3'="제조업")
        mdis$V20<- recode_factor(mdis$V20, '4'="건설업")
        mdis$V20<- recode_factor(mdis$V20, '5'="전기, 가스, 수도 및 위생서비스업")
        mdis$V20<- recode_factor(mdis$V20, '6'="상업")
        mdis$V20<- recode_factor(mdis$V20, '7'="운수업, 보관업, 통신업")
        mdis$V20<- recode_factor(mdis$V20, '8'="서비스업")
        mdis$V20<- recode_factor(mdis$V20, '9'="분류불능의 산업")
        mdis$V21<- recode_factor(mdis$V21, '1'="고용자")
        mdis$V21<- recode_factor(mdis$V21, '2'="자영업주")
        mdis$V21<- recode_factor(mdis$V21, '3'="가족종사자")
        mdis$V22<- recode_factor(mdis$V22, '1'="공가")
        mdis$V22<- recode_factor(mdis$V22, '2'="소유자")
        mdis$V22<- recode_factor(mdis$V22, '3'="세든 사람")
        mdis$V22<- recode_factor(mdis$V22, '4'="세없이 빌려사는 사람")
        mdis$V23<- recode_factor(mdis$V23, '1'="개인")
        mdis$V23<- recode_factor(mdis$V23, '2'="호텔, 하숙")
        mdis$V23<- recode_factor(mdis$V23, '3'="공공건물(병원, 기숙사, 고아원, 사찰)")
        mdis$V23<- recode_factor(mdis$V23, '4'="기타")
        mdis$V24<- recode_factor(mdis$V24, '1'="1년 미만")
        mdis$V24<- recode_factor(mdis$V24, '2'="1년 이상 ~ 6년 미만")
        mdis$V24<- recode_factor(mdis$V24, '3'="6년 이상 ~ 11년 미만")
        mdis$V24<- recode_factor(mdis$V24, '4'="11년 이상 ~ 16년 미만")
        mdis$V24<- recode_factor(mdis$V24, '5'="16년 이상 ~ 50년 미만")
        mdis$V24<- recode_factor(mdis$V24, '6'="50년이상")
        mdis$V25<- recode_factor(mdis$V25, '1'="1 개")
        mdis$V25<- recode_factor(mdis$V25, '2'="2 개")
        mdis$V25<- recode_factor(mdis$V25, '3'="3 개")
        mdis$V25<- recode_factor(mdis$V25, '4'="4 개")
        mdis$V25<- recode_factor(mdis$V25, '5'="5 개")
        mdis$V25<- recode_factor(mdis$V25, '6'="6 개")
        mdis$V25<- recode_factor(mdis$V25, '7'="7 개")
        mdis$V25<- recode_factor(mdis$V25, '8'="8 개")
        mdis$V25<- recode_factor(mdis$V25, '9'="9 개 이상")
        mdis$V26<- recode_factor(mdis$V26, '1'="2평 미만")
        mdis$V26<- recode_factor(mdis$V26, '2'="2평 이상 ~ 4평 미만")
        mdis$V26<- recode_factor(mdis$V26, '3'="4평 이상 ~ 6평 미만")
        mdis$V26<- recode_factor(mdis$V26, '4'="6평 이상 ~ 8평 미만")
        mdis$V26<- recode_factor(mdis$V26, '5'="8평 이상 ~ 10평 미만")
        mdis$V26<- recode_factor(mdis$V26, '6'="10평 이상")
        mdis$V27<- recode_factor(mdis$V27, '1'="없음")
        mdis$V27<- recode_factor(mdis$V27, '2'="1평 미만")
        mdis$V27<- recode_factor(mdis$V27, '3'="1평 이상 ~ 2평 미만")
        mdis$V27<- recode_factor(mdis$V27, '4'="2평 이상 ~ 3평 미만")
        mdis$V27<- recode_factor(mdis$V27, '5'="3평 이상 ~ 4평 미만")
        mdis$V27<- recode_factor(mdis$V27, '6'="4평 이상")
        mdis$V28<- recode_factor(mdis$V28, '1'="있음")
        mdis$V28<- recode_factor(mdis$V28, '2'="없음")
        mdis$V29<- recode_factor(mdis$V29, '1'="있음")
        mdis$V29<- recode_factor(mdis$V29, '2'="없음")
        mdis$V30<- recode_factor(mdis$V30, '1'="있음")
        mdis$V30<- recode_factor(mdis$V30, '2'="없음")
        mdis$V31<- recode_factor(mdis$V31, '1'="있음")
        mdis$V31<- recode_factor(mdis$V31, '2'="없음")
        mdis$V32<- recode_factor(mdis$V32, '1'="있음")
        mdis$V32<- recode_factor(mdis$V32, '2'="없음")
        mdis$V33<- recode_factor(mdis$V33, '1'="공동우물")
        mdis$V33<- recode_factor(mdis$V33, '2'="개인우물(펌프없음)")
        mdis$V33<- recode_factor(mdis$V33, '3'="개인우물(펌프있음)")
        mdis$V33<- recode_factor(mdis$V33, '4'="공동수도")
        mdis$V33<- recode_factor(mdis$V33, '5'="개인수도")
        mdis$V33<- recode_factor(mdis$V33, '6'="기타")
        mdis$V34<- recode_factor(mdis$V34, '1'="토혈식")
        mdis$V34<- recode_factor(mdis$V34, '2'="시멘트식")
        mdis$V34<- recode_factor(mdis$V34, '3'="수세식")
        mdis$V34<- recode_factor(mdis$V34, '4'="기타식")
        mdis$V34<- recode_factor(mdis$V34, '5'="없음")
        mdis$V35<- recode_factor(mdis$V35, '1'="있음")
        mdis$V35<- recode_factor(mdis$V35, '2'="없음")
        mdis$V36<- recode_factor(mdis$V36, '1'="있음")
        mdis$V36<- recode_factor(mdis$V36, '2'="없음")
        mdis$V37<- recode_factor(mdis$V37, '1'="있음")
        mdis$V37<- recode_factor(mdis$V37, '2'="없음")
        mdis$V38<- recode_factor(mdis$V38, '1'="있음")
        mdis$V38<- recode_factor(mdis$V38, '2'="없음")
        mdis$V39<- recode_factor(mdis$V39, '1'="있음")
        mdis$V39<- recode_factor(mdis$V39, '2'="없음")
        mdis$V40<- recode_factor(mdis$V40, '1'="있음")
        mdis$V40<- recode_factor(mdis$V40, '2'="없음")
        mdis$V40<- recode_factor(mdis$V40, '9'="미상")
        mdis$V40<- recode_factor(mdis$V40, '99'="미상")
        mdis$V43<- recode_factor(mdis$V43, '1'="정상적구조 떨어진것")
        mdis$V43<- recode_factor(mdis$V43, '2'="정상적구조 붙은것")
        mdis$V43<- recode_factor(mdis$V43, '3'="선박")
        mdis$V43<- recode_factor(mdis$V43, '4'="판자")
        mdis$V43<- recode_factor(mdis$V43, '5'="천막")
        mdis$V43<- recode_factor(mdis$V43, '6'="토막")
        mdis$V43<- recode_factor(mdis$V43, '7'="기타")
        mdis$V44<- recode_factor(mdis$V44, '1'="한식")
        mdis$V44<- recode_factor(mdis$V44, '2'="일본식")
        mdis$V44<- recode_factor(mdis$V44, '3'="흙부럭")
        mdis$V44<- recode_factor(mdis$V44, '4'="벽돌 또는 돌")
        mdis$V44<- recode_factor(mdis$V44, '5'="기타")
        mdis$V45<- recode_factor(mdis$V45, '1'="짚")
        mdis$V45<- recode_factor(mdis$V45, '2'="시멘트")
        mdis$V45<- recode_factor(mdis$V45, '3'="흙개와")
        mdis$V45<- recode_factor(mdis$V45, '4'="금속판")
        mdis$V45<- recode_factor(mdis$V45, '5'="스레이트")
        mdis$V45<- recode_factor(mdis$V45, '6'="기타")
        mdis$V46<- recode_factor(mdis$V46, '1'="양호(화재위험없음)")
        mdis$V46<- recode_factor(mdis$V46, '2'="요수리(화재위험있음)")
        mdis$V46<- recode_factor(mdis$V46, '3'="굴뚝이 없음")
        mdis$V47<- recode_factor(mdis$V47, '1'="일반적으로 양호함")
        mdis$V47<- recode_factor(mdis$V47, '2'="상당한 수리를 요함")
        mdis$V47<- recode_factor(mdis$V47, '3'="노후로 대수리 또는 재건축을 요함")
        mdis$V48<- recode_factor(mdis$V48, '1'="금년중-1년 미만")
        mdis$V48<- recode_factor(mdis$V48, '2'="6.25사변이후-1년 이상 ~ 10년 미만")
        mdis$V48<- recode_factor(mdis$V48, '3'="해방이후-10년이후 ~ 15년 미만")
        mdis$V48<- recode_factor(mdis$V48, '4'="중일전쟁이후-15년 이상 ~ 24년 미만")
        mdis$V48<- recode_factor(mdis$V48, '5'="한일합병이후-24년이상 ~ 50년 미만")
        mdis$V48<- recode_factor(mdis$V48, '6'="한일합병이전-50년이상")

colnames(mdis) = c("특별시.도"
, "일련번호", "영농비농", "행번호", "관계", "연령", "성별", "배우관계", "출생지", "국적", "출생아동수", "취학여부", "수학연수", "문맹여부", "주로한일", "일하였음", "구직", "이유", "직업", "산업", "종사상지위"
, "거주여부", "거주종류", "거주연수", "방수", "방평수", "대청마루", "목욕실", "광", "전등", "라디오", "외양간", "음료수", "변소", "부엌", "아궁이문없음", "아궁이문있음", "아궁이십구공탄", "아궁이기타", "사업체", "개인거주지"
, "집단거주지", "건물형태", "벽체", "지붕", "굴뚝", "건물상태", "건립연수", "가중치")

