#**********************************************************************  
#	*주의 사항
#		현재 스크립트 파일은 파일명만 출력되어 있습니다.
#		따라서, 저장된 추출 결과 파일의 경로를 'read.table' 또는 'read.fwf'에 추가하여야 합니다.
#	예) 다운로드 받은 폴더명 : C:\Download
#	  ※ 파일 경로 추가 : "[다운로드 받은 폴더명]\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt"
# 		read.table("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#		또는
#		read.fwf("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#
#		R 스크립트는 R 에서 파일 경로만 수정하시면 바로 실행(Ctrl+Alt+R)가능하며,
#		데이터셋 생성 후에 R 의 여러 가지 분석 기능을 사용할 수 있습니다.
#
#**********************************************************************

# install.packages("dplyr")
library(dplyr)

mdis <- read.table("rawdata/2020_2%_인구사항_20250821_05639.csv", header=FALSE, sep=",", colClasses = c("character"
, "character", "character", "character", "character", "character", "character", "numeric", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character"
, "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character"
, "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric"
, "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric", "character", "numeric", "character", "numeric", "numeric", "character", "character", "character", "character", "character"
, "character", "character", "character", "character", "character", "character", "character", "character", "numeric"), skip=1, na.string=c("*","**","***","****","*****","******","*******","********","*********","**********","."))

saveRDS(mdis, "data/tscensus2020.rds")


        mdis$V1<- recode_factor(mdis$V1, '11'="서울특별시")
        mdis$V1<- recode_factor(mdis$V1, '21'="부산광역시")
        mdis$V1<- recode_factor(mdis$V1, '22'="대구광역시")
        mdis$V1<- recode_factor(mdis$V1, '23'="인천광역시")
        mdis$V1<- recode_factor(mdis$V1, '24'="광주광역시")
        mdis$V1<- recode_factor(mdis$V1, '25'="대전광역시")
        mdis$V1<- recode_factor(mdis$V1, '26'="울산광역시")
        mdis$V1<- recode_factor(mdis$V1, '29'="세종특별자치시")
        mdis$V1<- recode_factor(mdis$V1, '31'="경기도")
        mdis$V1<- recode_factor(mdis$V1, '32'="강원도")
        mdis$V1<- recode_factor(mdis$V1, '33'="충청북도")
        mdis$V1<- recode_factor(mdis$V1, '34'="충청남도")
        mdis$V1<- recode_factor(mdis$V1, '35'="전라북도")
        mdis$V1<- recode_factor(mdis$V1, '36'="전라남도")
        mdis$V1<- recode_factor(mdis$V1, '37'="경상북도")
        mdis$V1<- recode_factor(mdis$V1, '38'="경상남도")
        mdis$V1<- recode_factor(mdis$V1, '39'="제주특별자치도")
        mdis$V4<- recode_factor(mdis$V4, '1'="읍부")
        mdis$V4<- recode_factor(mdis$V4, '2'="면부")
        mdis$V4<- recode_factor(mdis$V4, '3'="동부")
        mdis$V6<- recode_factor(mdis$V6, '1'="일반조사구")
        mdis$V6<- recode_factor(mdis$V6, '2'="섬조사구")
        mdis$V6<- recode_factor(mdis$V6, 'A'="아파트조사구")
        mdis$V7<- recode_factor(mdis$V7, '1'="남자")
        mdis$V7<- recode_factor(mdis$V7, '2'="여자")
        mdis$V9<- recode_factor(mdis$V9, '01'="가구주(본인)")
        mdis$V9<- recode_factor(mdis$V9, '02'="배우자")
        mdis$V9<- recode_factor(mdis$V9, '03'="자녀")
        mdis$V9<- recode_factor(mdis$V9, '04'="자녀의 배우자")
        mdis$V9<- recode_factor(mdis$V9, '05'="가구주의 부모")
        mdis$V9<- recode_factor(mdis$V9, '06'="배우자의 부모")
        mdis$V9<- recode_factor(mdis$V9, '07'="손주, 손주의 배우자(외손주 포함)")
        mdis$V9<- recode_factor(mdis$V9, '08'="증손주, 증손주의 배우자")
        mdis$V9<- recode_factor(mdis$V9, '09'="조부모")
        mdis$V9<- recode_factor(mdis$V9, '10'="형제자매, 형제자매의 배우자")
        mdis$V9<- recode_factor(mdis$V9, '11'="형제자매의 자녀, 형제자매의 자녀의 배우자")
        mdis$V9<- recode_factor(mdis$V9, '12'="부모의 형제자매, 부모의 형제자매의 배우자")
        mdis$V9<- recode_factor(mdis$V9, '13'="기타 친인척")
        mdis$V9<- recode_factor(mdis$V9, '14'="그 외 같이 사는 사람(고용인, 하숙인 등)")
        mdis$V10<- recode_factor(mdis$V10, '1'="받지않았음(미취학포함)")
        mdis$V10<- recode_factor(mdis$V10, '2'="초등학교")
        mdis$V10<- recode_factor(mdis$V10, '3'="중학교")
        mdis$V10<- recode_factor(mdis$V10, '4'="고등학교")
        mdis$V10<- recode_factor(mdis$V10, '5'="대학교(2,3년제)")
        mdis$V10<- recode_factor(mdis$V10, '6'="대학교(4년제 이상)")
        mdis$V10<- recode_factor(mdis$V10, '7'="대학원 석사 과정")
        mdis$V10<- recode_factor(mdis$V10, '8'="대학원 박사 과정")
        mdis$V11<- recode_factor(mdis$V11, '1'="졸업")
        mdis$V11<- recode_factor(mdis$V11, '2'="재학")
        mdis$V11<- recode_factor(mdis$V11, '3'="수료")
        mdis$V11<- recode_factor(mdis$V11, '4'="휴학")
        mdis$V11<- recode_factor(mdis$V11, '5'="중퇴")
        mdis$V12<- recode_factor(mdis$V12, '1'="대한민국")
        mdis$V12<- recode_factor(mdis$V12, '2'="외국")
        mdis$V13<- recode_factor(mdis$V13, '1'="대한민국")
        mdis$V13<- recode_factor(mdis$V13, '2'="외국")
        mdis$V14<- recode_factor(mdis$V14, '1'="응답")
        mdis$V15<- recode_factor(mdis$V15, '1'="응답")
        mdis$V16<- recode_factor(mdis$V16, '1'="현재 살고 있는 집")
        mdis$V16<- recode_factor(mdis$V16, '2'="같은 시군구 내 다른 집")
        mdis$V16<- recode_factor(mdis$V16, '3'="다른 시군구")
        mdis$V16<- recode_factor(mdis$V16, '4'="북한 또는 외국")
        mdis$V17<- recode_factor(mdis$V17, '1'="응답")
        mdis$V18<- recode_factor(mdis$V18, '1'="태어나지 않았음")
        mdis$V18<- recode_factor(mdis$V18, '2'="비이동(현재 살고있는 집+같은 읍면동 내 다른 집)")
        mdis$V18<- recode_factor(mdis$V18, '3'="같은 시군구 내 다른 집")
        mdis$V18<- recode_factor(mdis$V18, '4'="다른 시군구")
        mdis$V18<- recode_factor(mdis$V18, '5'="북한 또는 외국")
        mdis$V19<- recode_factor(mdis$V19, '11'="서울특별시")
        mdis$V19<- recode_factor(mdis$V19, '21'="부산광역시")
        mdis$V19<- recode_factor(mdis$V19, '22'="대구광역시")
        mdis$V19<- recode_factor(mdis$V19, '23'="인천광역시")
        mdis$V19<- recode_factor(mdis$V19, '24'="광주광역시")
        mdis$V19<- recode_factor(mdis$V19, '25'="대전광역시")
        mdis$V19<- recode_factor(mdis$V19, '26'="울산광역시")
        mdis$V19<- recode_factor(mdis$V19, '29'="세종특별자치시")
        mdis$V19<- recode_factor(mdis$V19, '31'="경기도")
        mdis$V19<- recode_factor(mdis$V19, '32'="강원도")
        mdis$V19<- recode_factor(mdis$V19, '33'="충청북도")
        mdis$V19<- recode_factor(mdis$V19, '34'="충청남도")
        mdis$V19<- recode_factor(mdis$V19, '35'="전라북도")
        mdis$V19<- recode_factor(mdis$V19, '36'="전라남도")
        mdis$V19<- recode_factor(mdis$V19, '37'="경상북도")
        mdis$V19<- recode_factor(mdis$V19, '38'="경상남도")
        mdis$V19<- recode_factor(mdis$V19, '39'="제주특별자치도")
        mdis$V20<- recode_factor(mdis$V20, '1'="응답")
        mdis$V21<- recode_factor(mdis$V21, '1'="태어나지 않았음")
        mdis$V21<- recode_factor(mdis$V21, '2'="비이동(현재 살고있는 집+같은 읍면동 내 다른 집)")
        mdis$V21<- recode_factor(mdis$V21, '3'="같은 시군구 내 다른 집")
        mdis$V21<- recode_factor(mdis$V21, '4'="다른 시군구")
        mdis$V21<- recode_factor(mdis$V21, '5'="북한 또는 외국")
        mdis$V22<- recode_factor(mdis$V22, '1'="응답")
        mdis$V23<- recode_factor(mdis$V23, '11'="서울특별시")
        mdis$V23<- recode_factor(mdis$V23, '21'="부산광역시")
        mdis$V23<- recode_factor(mdis$V23, '22'="대구광역시")
        mdis$V23<- recode_factor(mdis$V23, '23'="인천광역시")
        mdis$V23<- recode_factor(mdis$V23, '24'="광주광역시")
        mdis$V23<- recode_factor(mdis$V23, '25'="대전광역시")
        mdis$V23<- recode_factor(mdis$V23, '26'="울산광역시")
        mdis$V23<- recode_factor(mdis$V23, '29'="세종특별자치시")
        mdis$V23<- recode_factor(mdis$V23, '31'="경기도")
        mdis$V23<- recode_factor(mdis$V23, '32'="강원도")
        mdis$V23<- recode_factor(mdis$V23, '33'="충청북도")
        mdis$V23<- recode_factor(mdis$V23, '34'="충청남도")
        mdis$V23<- recode_factor(mdis$V23, '35'="전라북도")
        mdis$V23<- recode_factor(mdis$V23, '36'="전라남도")
        mdis$V23<- recode_factor(mdis$V23, '37'="경상북도")
        mdis$V23<- recode_factor(mdis$V23, '38'="경상남도")
        mdis$V23<- recode_factor(mdis$V23, '39'="제주특별자치도")
        mdis$V24<- recode_factor(mdis$V24, '1'="응답")
        mdis$V25<- recode_factor(mdis$V25, '1'="그렇다")
        mdis$V25<- recode_factor(mdis$V25, '2'="아니다")
        mdis$V26<- recode_factor(mdis$V26, '11'="서울특별시")
        mdis$V26<- recode_factor(mdis$V26, '21'="부산광역시")
        mdis$V26<- recode_factor(mdis$V26, '22'="대구광역시")
        mdis$V26<- recode_factor(mdis$V26, '23'="인천광역시")
        mdis$V26<- recode_factor(mdis$V26, '24'="광주광역시")
        mdis$V26<- recode_factor(mdis$V26, '25'="대전광역시")
        mdis$V26<- recode_factor(mdis$V26, '26'="울산광역시")
        mdis$V26<- recode_factor(mdis$V26, '29'="세종특별자치시")
        mdis$V26<- recode_factor(mdis$V26, '31'="경기도")
        mdis$V26<- recode_factor(mdis$V26, '32'="강원도")
        mdis$V26<- recode_factor(mdis$V26, '33'="충청북도")
        mdis$V26<- recode_factor(mdis$V26, '34'="충청남도")
        mdis$V26<- recode_factor(mdis$V26, '35'="전라북도")
        mdis$V26<- recode_factor(mdis$V26, '36'="전라남도")
        mdis$V26<- recode_factor(mdis$V26, '37'="경상북도")
        mdis$V26<- recode_factor(mdis$V26, '38'="경상남도")
        mdis$V26<- recode_factor(mdis$V26, '39'="제주특별자치도")
        mdis$V27<- recode_factor(mdis$V27, '1'="그렇다")
        mdis$V27<- recode_factor(mdis$V27, '2'="아니다")
        mdis$V28<- recode_factor(mdis$V28, '1'="응답")
        mdis$V29<- recode_factor(mdis$V29, '1'="응답")
        mdis$V30<- recode_factor(mdis$V30, '1'="응답")
        mdis$V31<- recode_factor(mdis$V31, '1'="통근함")
        mdis$V31<- recode_factor(mdis$V31, '2'="통학함")
        mdis$V31<- recode_factor(mdis$V31, '3'="안함")
        mdis$V32<- recode_factor(mdis$V32, '1'="현재 살고 있는 읍면동")
        mdis$V32<- recode_factor(mdis$V32, '2'="다른 읍면동")
        mdis$V33<- recode_factor(mdis$V33, '1'="응답")
        mdis$V34<- recode_factor(mdis$V34, '1'="응답")
        mdis$V35<- recode_factor(mdis$V35, '1'="그렇다")
        mdis$V35<- recode_factor(mdis$V35, '2'="아니다")
        mdis$V36<- recode_factor(mdis$V36, '1'="주로 일하였음")
        mdis$V36<- recode_factor(mdis$V36, '2'="틈틈이 일하였음")
        mdis$V36<- recode_factor(mdis$V36, '3'="일시휴직")
        mdis$V36<- recode_factor(mdis$V36, '4'="일하지 않았음")
        mdis$V37<- recode_factor(mdis$V37, '1'="그렇다")
        mdis$V37<- recode_factor(mdis$V37, '2'="아니다")
        mdis$V38<- recode_factor(mdis$V38, '1'="임금근로자")
        mdis$V38<- recode_factor(mdis$V38, '2'="고용원이 없는 자영업자")
        mdis$V38<- recode_factor(mdis$V38, '3'="고용원이 있는 자영업자")
        mdis$V38<- recode_factor(mdis$V38, '4'="무급가족종사자")
        mdis$V39<- recode_factor(mdis$V39, 'A'="농업, 임업 및 어업")
        mdis$V39<- recode_factor(mdis$V39, 'B'="광업")
        mdis$V39<- recode_factor(mdis$V39, 'C'="제조업")
        mdis$V39<- recode_factor(mdis$V39, 'D'="전기,가스,증기 및 공기 조절 공급업")
        mdis$V39<- recode_factor(mdis$V39, 'E'="수도, 하수 및 폐기물 처리, 원료 재생업")
        mdis$V39<- recode_factor(mdis$V39, 'F'="건설업")
        mdis$V39<- recode_factor(mdis$V39, 'G'="도매 및 소매업")
        mdis$V39<- recode_factor(mdis$V39, 'H'="운수 및 창고업")
        mdis$V39<- recode_factor(mdis$V39, 'I'="숙박 및 음식점업")
        mdis$V39<- recode_factor(mdis$V39, 'J'="정보통신업")
        mdis$V39<- recode_factor(mdis$V39, 'K'="금융 및 보험업")
        mdis$V39<- recode_factor(mdis$V39, 'L'="부동산업")
        mdis$V39<- recode_factor(mdis$V39, 'M'="전문, 과학 및 기술 서비스업")
        mdis$V39<- recode_factor(mdis$V39, 'N'="사업시설 관리, 사업 지원 및 임대 서비스업")
        mdis$V39<- recode_factor(mdis$V39, 'O'="공공행정, 국방 및 사회보장 행정")
        mdis$V39<- recode_factor(mdis$V39, 'P'="교육 서비스업")
        mdis$V39<- recode_factor(mdis$V39, 'Q'="보건업 및 사회복지 서비스업")
        mdis$V39<- recode_factor(mdis$V39, 'R'="예술, 스포츠 및 여가관련 서비스업")
        mdis$V39<- recode_factor(mdis$V39, 'S'="협회 및 단체, 수리 및 기타 개인 서비스업")
        mdis$V39<- recode_factor(mdis$V39, 'T'="가구 내 고용활동 및 달리 분류되지 않은 자가 소비 생산활동")
        mdis$V39<- recode_factor(mdis$V39, 'U'="국제 및 외국기관")
        mdis$V39<- recode_factor(mdis$V39, 'Z'="경제활동을 하지 않는 사람(결측값)")
        mdis$V40<- recode_factor(mdis$V40, '1'="그렇다")
        mdis$V40<- recode_factor(mdis$V40, '2'="아니다")
        mdis$V41<- recode_factor(mdis$V41, '1'="관리자")
        mdis$V41<- recode_factor(mdis$V41, '2'="전문가 및 관련 종사자")
        mdis$V41<- recode_factor(mdis$V41, '3'="사무 종사자")
        mdis$V41<- recode_factor(mdis$V41, '4'="서비스 종사자")
        mdis$V41<- recode_factor(mdis$V41, '5'="판매 종사자")
        mdis$V41<- recode_factor(mdis$V41, '6'="농림어업 숙련 종사자")
        mdis$V41<- recode_factor(mdis$V41, '7'="기능원 및 관련 기능 종사자")
        mdis$V41<- recode_factor(mdis$V41, '8'="장치기계 조작 및 조립 종사자")
        mdis$V41<- recode_factor(mdis$V41, '9'="단순노무 종사자")
        mdis$V41<- recode_factor(mdis$V41, 'A'="기타")
        mdis$V42<- recode_factor(mdis$V42, '1'="그렇다")
        mdis$V42<- recode_factor(mdis$V42, '2'="아니다")
        mdis$V43<- recode_factor(mdis$V43, '1'="사업장")
        mdis$V43<- recode_factor(mdis$V43, '2'="자기 집")
        mdis$V43<- recode_factor(mdis$V43, '3'="남의 집")
        mdis$V43<- recode_factor(mdis$V43, '4'="거리")
        mdis$V43<- recode_factor(mdis$V43, '5'="야외 작업 현장")
        mdis$V43<- recode_factor(mdis$V43, '6'="운송 수단")
        mdis$V43<- recode_factor(mdis$V43, '7'="기타")
        mdis$V44<- recode_factor(mdis$V44, '1'="미혼")
        mdis$V44<- recode_factor(mdis$V44, '2'="배우자 있음")
        mdis$V44<- recode_factor(mdis$V44, '3'="사별")
        mdis$V44<- recode_factor(mdis$V44, '4'="이혼")
        mdis$V45<- recode_factor(mdis$V45, '1'="6개월 미만")
        mdis$V45<- recode_factor(mdis$V45, '2'="6개월 이상")
        mdis$V46<- recode_factor(mdis$V46, '1'="필요함")
        mdis$V46<- recode_factor(mdis$V46, '2'="필요하지 않음")
        mdis$V47<- recode_factor(mdis$V47, '1'="6개월 미만")
        mdis$V47<- recode_factor(mdis$V47, '2'="6개월 이상~1년 미만")
        mdis$V47<- recode_factor(mdis$V47, '3'="1년~3년 미만")
        mdis$V47<- recode_factor(mdis$V47, '4'="3년~5년 미만")
        mdis$V47<- recode_factor(mdis$V47, '5'="5년~10년 미만")
        mdis$V47<- recode_factor(mdis$V47, '6'="10년~15년 미만")
        mdis$V47<- recode_factor(mdis$V47, '7'="15년~20년 미만")
        mdis$V47<- recode_factor(mdis$V47, '8'="20년 이상")
        mdis$V48<- recode_factor(mdis$V48, '11'="서울특별시")
        mdis$V48<- recode_factor(mdis$V48, '21'="부산광역시")
        mdis$V48<- recode_factor(mdis$V48, '22'="대구광역시")
        mdis$V48<- recode_factor(mdis$V48, '23'="인천광역시")
        mdis$V48<- recode_factor(mdis$V48, '24'="광주광역시")
        mdis$V48<- recode_factor(mdis$V48, '25'="대전광역시")
        mdis$V48<- recode_factor(mdis$V48, '26'="울산광역시")
        mdis$V48<- recode_factor(mdis$V48, '29'="세종특별자치시")
        mdis$V48<- recode_factor(mdis$V48, '31'="경기도")
        mdis$V48<- recode_factor(mdis$V48, '32'="강원도")
        mdis$V48<- recode_factor(mdis$V48, '33'="충청북도")
        mdis$V48<- recode_factor(mdis$V48, '34'="충청남도")
        mdis$V48<- recode_factor(mdis$V48, '35'="전라북도")
        mdis$V48<- recode_factor(mdis$V48, '36'="전라남도")
        mdis$V48<- recode_factor(mdis$V48, '37'="경상북도")
        mdis$V48<- recode_factor(mdis$V48, '38'="경상남도")
        mdis$V48<- recode_factor(mdis$V48, '39'="제주특별자치도")
        mdis$V49<- recode_factor(mdis$V49, '1'="응답")
        mdis$V50<- recode_factor(mdis$V50, '1'="응답")
        mdis$V51<- recode_factor(mdis$V51, '1'="응답")
        mdis$V52<- recode_factor(mdis$V52, '1'="응답")
        mdis$V53<- recode_factor(mdis$V53, '1'="응답")
        mdis$V54<- recode_factor(mdis$V54, '1'="응답")
        mdis$V55<- recode_factor(mdis$V55, '1'="응답")
        mdis$V56<- recode_factor(mdis$V56, '1'="1명")
        mdis$V56<- recode_factor(mdis$V56, '2'="2명")
        mdis$V56<- recode_factor(mdis$V56, '3'="3명")
        mdis$V56<- recode_factor(mdis$V56, '4'="4명 이상")
        mdis$V57<- recode_factor(mdis$V57, '1'="응답")
        mdis$V58<- recode_factor(mdis$V58, '1'="응답")
        mdis$V59<- recode_factor(mdis$V59, '1'="응답")
        mdis$V60<- recode_factor(mdis$V60, '1'="응답")
        mdis$V62<- recode_factor(mdis$V62, '1'="사회분야단체")
        mdis$V63<- recode_factor(mdis$V63, '1'="경제분야단체")
        mdis$V64<- recode_factor(mdis$V64, '1'="문화분야단체")
        mdis$V65<- recode_factor(mdis$V65, '1'="정치분야단체")
        mdis$V66<- recode_factor(mdis$V66, '1'="종교분야단체")
        mdis$V67<- recode_factor(mdis$V67, '1'="지역단체")
        mdis$V68<- recode_factor(mdis$V68, '1'="친목단체")
        mdis$V69<- recode_factor(mdis$V69, '1'="15세미만")
        mdis$V69<- recode_factor(mdis$V69, '2'="15-19세")
        mdis$V69<- recode_factor(mdis$V69, '3'="20-24세")
        mdis$V69<- recode_factor(mdis$V69, '4'="25-29세")
        mdis$V69<- recode_factor(mdis$V69, '5'="30-34세")
        mdis$V69<- recode_factor(mdis$V69, '6'="35-39세")
        mdis$V69<- recode_factor(mdis$V69, '7'="40세이상")
        mdis$V70<- recode_factor(mdis$V70, '1'="교육단체")
        mdis$V72<- recode_factor(mdis$V72, '1'="기타")
        mdis$V74<- recode_factor(mdis$V74, '1'="해당없음")
        mdis$V77<- recode_factor(mdis$V77, '1'="있음")
        mdis$V77<- recode_factor(mdis$V77, '2'="없음")
        mdis$V78<- recode_factor(mdis$V78, '1'="있음")
        mdis$V78<- recode_factor(mdis$V78, '2'="없음")
        mdis$V79<- recode_factor(mdis$V79, '1'="있음")
        mdis$V79<- recode_factor(mdis$V79, '2'="없음")
        mdis$V80<- recode_factor(mdis$V80, '1'="본인의 일")
        mdis$V81<- recode_factor(mdis$V81, '1'="금융자산")
        mdis$V82<- recode_factor(mdis$V82, '1'="배우자의 일")
        mdis$V83<- recode_factor(mdis$V83, '1'="개인연금")
        mdis$V84<- recode_factor(mdis$V84, '1'="공적연금")
        mdis$V85<- recode_factor(mdis$V85, '1'="부동산업")
        mdis$V86<- recode_factor(mdis$V86, '1'="자녀의 도움")
        mdis$V87<- recode_factor(mdis$V87, '1'="부모의 도움")
        mdis$V88<- recode_factor(mdis$V88, '1'="국가 및 지방자지단체의 보조")
        mdis$V89<- recode_factor(mdis$V89, '1'="기타")

                
colnames(mdis) = c("행정구역시도코드"
, "가구일련번호", "행정구역시군구코드", "동읍면부_구분코드", "가구원번호", "조사구특성코드", "성별코드", "만연령", "가구주관계코드", "교육정도코드", "수학구분코드", "출생국적_대한민국여부", "현재국적_대한민국여부", "아동보육_부모_돌봄주체여부", "아동보육_조부모_돌봄주체여부", "출생지구분코드", "아동보육_기타가족및친인척_돌봄주체여부", "5년전거주지_구분코드", "출생지_타행정구역시도코드", "아동보육_가사도우미및이웃사람_돌봄주체여부", "1년전거주지_구분코드"
, "아동보육_유치원_돌봄주체여부", "1년전거주지_타시도행정구역코드", "아동보육_어린이집및놀이방_돌봄주체여부", "활동제약_정신적제약_지속여부", "5년전거주지_타시도행정구역코드", "활동제약_육체적제약_지속여부", "아동보육_방과후학교_돌봄주체여부", "아동보육_학원_돌봄주체여부", "아동보육_혼자및아동끼리지냄_돌봄주체여부", "통근통학구분코드", "통근통학장소코드", "아동보육_지역아동센터_돌봄주체여부", "아동보육_기타_돌봄주체여부", "활동제약_시각장애_지속여부", "경제활동상태코드", "활동제약_청각장애_지속여부", "종사상지위코드", "산업대분류코드", "활동제약_언어장애_지속여부", "직업대분류코드"
, "활동제약_지적자폐성장애_지속여부", "근로장소코드", "혼인상태코드", "활동제약_지속기간코드", "활동제약_돌봄필요여부", "현직업근무년수코드", "통근통학_타행정구역읍면동코드", "교통수단_도보여부", "교통수단_자전거_이용여부", "교통수단_승용차및소형승합차_이용여부", "교통수단_시내좌석마을버스_이용여부", "교통수단_통근통학버스이용_이용여부", "교통수단_트럭_이용여부", "교통수단_고속시외버스_이용여부", "추가계획자녀수", "교통수단_전철지하철_이용여부", "교통수단_기차_이용여부", "교통수단_택시_이용여부", "교통수단_기타_이용여부", "통근통학_소요분수"
, "사회활동_사회분야단체_참여및활동여부", "사회활동_경제분야단체_참여및활동여부", "사회활동_문화분야단체_참여및활동여부", "사회활동_정치분야단체_참여및활동여부", "사회활동_종교분야단체_참여및활동여부", "사회활동_지역단체_참여및활동여부", "사회활동_친목단체_참여및활동여부", "초혼연령코드", "사회활동_교육단체_참여및활동여부", "남아출산수", "사회활동_기타_참여및활동여부", "여아출산수", "사회활동_없음_참여및활동여부", "남아사망수", "여아사망수", "추가자녀계획유무", "결혼전취업유무", "경력단절유무", "고령자생활비원천_본인직업_생활비마련여부", "고령자생활비원천_예금적금_생활비마련여부"
, "고령자생활비원천_배우자직업_생활비마련여부", "고령자생활비원천_개인연금_생활비마련여부", "고령자생활비원천_공적연금_생활비마련여부", "고령자생활비원천_부동산_생활비마련여부", "고령자생활비원천_동거자녀_생활비마련여부", "고령자생활비원천_부모_생활비마련여부", "고령자생활비원천_국가지자체보조_생활비마련여부", "고령자생활비원천_기타_생활비마련여부", "인구가중값")

